# Generated by Django 4.2 on 2023-04-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preadvice',
            name='preadvice_status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Received'), ('P', 'Partially received')], max_length=1),
        ),
    ]
