# Generated by Django 4.2 on 2023-04-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_preadviceitem_received_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='preadviceitem',
            name='preadvice_status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Received'), ('S', 'Partially received')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
