# Generated by Django 4.2 on 2023-04-20 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_supplier_alter_preadvice_preadvice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preadviceitem',
            name='received_location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
    ]
