# Generated by Django 4.2 on 2023-04-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(default='Location'),
        ),
    ]
