# Generated by Django 4.2 on 2023-04-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApplication', '0002_location_capacity_alter_location_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='source_location',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='preadvice',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='preadvice',
            name='items',
        ),
        migrations.RemoveField(
            model_name='preadvice',
            name='source_location',
        ),
        migrations.RemoveField(
            model_name='preadviceitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='preadviceitem',
            name='preadvice',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='location',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='PreAdvice',
        ),
        migrations.DeleteModel(
            name='PreAdviceItem',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
